name: run

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Init
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make

    - name: Run tests
      run: |
        make example-test
        make submit

    - name: Commit files
      run: |
        sha=$(git rev-parse HEAD)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add result/${sha}/*
        result=$(head -1 result/${sha}/result.txt | sed -r 's/^.*\"score\":\"([^\"]*)\".*$/score=\1/')
        git commit -m "$result"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}